spring:
  application:
    name: authservice

  datasource:
    url: jdbc:mysql://localhost:3306/taas_db?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false&&createDatabaseIfNotExist=true
    username: root
    password: root
    #driveri-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    database-platform: org.hibernate.dialect.MySQL5Dialect

eureka:
  instance:
    preferIpAddress: true
    appname: authservice
  client:
    enabled: true
    serviceUrl:
      #defaultZone: http://service-discovery-server:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081

frontend:
  url: http://localhost:5173 

