spring:
  application:
    name: auth_service
  main:
    allow-bean-definition-overriding: true
  datasource:
    #url: jdbc:mysql:${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    url: jdbc:mysql://localhost:3306/taas_db?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false&&createDatabaseIfNotExist=true
    username: root
    password: root
    driveri-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    database-platform: org.hibernate.dialect.MySQL5Dialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 611783894582-gbcl6d7lidpkfpgjuk0qoihfe1tme2j9.apps.googleusercontent.com
            client-secret: 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

eureka:
  instance:
    preferIpAddress: true
    appname: auth-service
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://service-discovery-server:8761/eureka/

server:
  port: 8081

frontend:
  url: http://localhost:5173

