spring:
  application:
    name: service-storage
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin

eureka:
  instance:
    preferIpAddress: true
    appname: service-storage
  client:
    serviceUrl:
      defaultZone: http://service-discovery-server:8761/eureka/
      #defaultZone: http://localhost:8761/eureka/

server:
  port: 8085