apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-client
  template:
    metadata:
      labels:
        app: service-client
    spec:
      containers:
        - name: service-client
          image: service-client:fuego
          ports:
            - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  type: LoadBalancer
  selector:
    app: service-client
  ports:
    - port: 5173
      targetPort: 5173
      nodePort: 30000