apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-chat
  template:
    metadata:
      labels:
        app: db-chat
    spec:
      containers:
        - name: db-chat
          image: mysql:5.7
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: chat_db
---
apiVersion: v1
kind: Service
metadata:
  name: db-chat
spec:
  selector:
    app: db-chat
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
