apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-reviews
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-reviews
  template:
    metadata:
      labels:
        app: db-reviews
    spec:
      containers:
        - name: db-reviews
          image: mysql:5.7
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: reviews_db
---
apiVersion: v1
kind: Service
metadata:
  name: db-reviews
spec:
  selector:
    app: db-reviews
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
