apiVersion: apps/v1
kind: Deployment
metadata:
    name: db-storage
spec:
    replicas: 1
    selector:
        matchLabels:
            app: db-storage
    template:
        metadata:
            labels:
                app: db-storage
        spec:
            containers:
            - 
                name: db-storage
                image: mysql:5.7
                ports:
                - containerPort: 3306
                env:
                - 
                    name: MYSQL_ROOT_PASSWORD
                    value: root
                - 
                    name: MYSQL_DATABASE
                    value: storage_db
---
apiVersion: v1
kind: Service
metadata:
    name: db-storage
spec:
    selector:
        app: db-storage
    ports:
    - 
        protocol: TCP
        port: 3306
        targetPort: 3306