apiVersion: apps/v1
kind: Deployment
metadata:
    name: db-user
spec:
    replicas: 1
    selector:
        matchLabels:
            app: db-user
    template:
        metadata:
            labels:
                app: db-user
        spec:
            containers:
            - 
                name: db-user
                image: mysql:5.7
                ports:
                - containerPort: 3306
                env:
                - 
                    name: MYSQL_ROOT_PASSWORD
                    value: root
                - 
                    name: MYSQL_DATABASE
                    value: user_db
---
apiVersion: v1
kind: Service
metadata:
  name: db-user
spec:
  selector:
    app: db-user
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306