apiVersion: apps/v1
kind: Deployment
metadata:
    name: service-discovery-server
spec:
    replicas: 1
    selector:
        matchLabels:
            app: service-discovery-server
    template:
        metadata:
            labels:
                app: service-discovery-server
        spec:
            containers:
            - name: service-discovery-server
            image: 
                name: service-discovery-server:latest
                ports:
                - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
    name: service-discovery-server
spec:
    selector:
        app: service-discovery-server
    ports:
    - 
        protocol: TCP
        port: 8761
        targetPort: 8761                    