version: '3.7'
services:
 demo:
    image: filmserie:latest
    ports:
      - "8081:8081"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-discovery-server:8761/eureka/
    depends_on:
      - service-discovery-server
      
    networks:
      - opnet
 service-discovery-server:
    image: service_discovery_server
    ports:
      - "8761:8761"
    expose:
      - "8761"
    networks:
      - opnet

 api-gateway:
    image: api_gateway
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-discovery-server:8761/eureka/
    ports:
      - "8080:8080"
    depends_on:
      - service-discovery-server
    networks:
      - opnet

networks:
  opnet:
    driver: bridge