version: '3.8'
services:
  auth-service:
    image: service_auth:latest
    ports:
      - "8081:8081"
    links:
      - "userdb"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-discovery-server:8761/eureka/
      - spring.datasource.url=jdbc:mysql://userdb:3306/taas_db?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
  
    depends_on:
      - userdb
      - service-discovery-server
    networks:
      - opnet
      
  review-service:
      image: service_reviews:latest
      ports:
      - "8083:8083"
      links:
      - "userdb"
      environment:
      - eureka.client.serviceUrl.defaultZone=http://service-discovery-server:8761/eureka/
      - spring.datasource.url=jdbc:mysql://userdb:3306/taas_db?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
  
      depends_on:
      - userdb
      - service-discovery-server
      networks:
      - opnet


    
  service-discovery-server:
    image: service_discovery_server
    ports:
      - "8761:8761"
    expose:
      - "8761"
    networks:
      - opnet

  api-gateway:
    image: service_gateway:latest
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-discovery-server:8761/eureka/
    ports:
      - "8080:8080"
    depends_on:
      - service-discovery-server
    networks:
      - opnet
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
  
  userdb:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      #MYSQL_DATABASE: taas_db
      
    ports:
      - "3306:3306"
    networks:
      - opnet

  phpmyadmin:
     image: phpmyadmin/phpmyadmin
     container_name: taas_pma
     environment:
       PMA_HOST: userdb
       PMA_PORT: 3306
       PMA_ARBITRARY: 1
     restart: always
     ports:
       - 8067:80
     networks:
      - opnet


networks:
  opnet:
    driver: bridge