version: "3.8"
services:
  # MANAGEMENT
  rabbitmq:
    image: rabbitmq:3.9.8-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - opnet
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  service-discovery-server:
    image: service-discovery-server:fuego
    ports:
      - "8761:8761"
    expose:
      - "8761"
    networks:
      - opnet

  service-gateway:
    image: service-gateway:fuego
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-discovery-server:8761/eureka/
    ports:
      - "8080:8080"
    depends_on:
      - service-discovery-server
      - rabbitmq
    networks:
      - opnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: taas_pma
    restart: always
    ports:
      - 8086:80
    environment:
      - PMA_HOSTS=db-user, db-storage, db-chat, db-reviews
      - PMA_USER=root
      - PMA_PASSWORD=root
    depends_on:
      - db-user
      - db-storage
      - db-chat
      - db-reviews
    networks:
      - opnet

  db-user:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_db
    ports:
      - "3306:3306"
    networks:
      - opnet

  db-storage:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: storage_db
    ports:
      - "3307:3307"
    networks:
      - opnet

  db-chat:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat_db
    ports:
      - "3308:3308"
    networks:
      - opnet

  db-reviews:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reviews_db
    ports:
      - "3309:3309"
    networks:
      - opnet

  service-notifications:
    image: service-notifications:fuego
    ports:
      - "8082:8082"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-discovery-server:8761/eureka/
    depends_on:
      - service-discovery-server
      - rabbitmq
    networks:
      - opnet

  # AUTHENTICATION
  service-auth:
    image: service-auth:fuego
    ports:
      - "8081:8081"
    links:
      - "db-user"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-discovery-server:8761/eureka/
      - spring.datasource.url=jdbc:mysql://db-user:3306/user_db?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      - spring.datasource.username=root
      - spring.datasource.password=root
    depends_on:
      - db-user
      - service-discovery-server
      - rabbitmq
    networks:
      - opnet

  # REVIEWS
  service-reviews:
    image: service-reviews:fuego
    ports:
      - "8083:8083"
    links:
      - "db-reviews"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-discovery-server:8761/eureka/
      - spring.datasource.url=jdbc:mysql://db-reviews:3306/reviews_db?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      - spring.datasource.username=root
      - spring.datasource.password=root

      # - spring.datasource.url=jdbc:mysql://db-reviews:3309/reviews_db?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    depends_on:
      - db-reviews
      - service-discovery-server
      - rabbitmq
    networks:
      - opnet
  
  service-chat:
    image: service-chat:fuego
    ports:
      - "8084:8084"
    links:
      - "db-chat"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-discovery-server:8761/eureka/
      - spring.datasource.url=jdbc:mysql://db-chat:3306/chat_db?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      - spring.datasource.username=root
      - spring.datasource.password=root
    depends_on:
      - db-chat
      - service-discovery-server
      - rabbitmq
    networks:
      - opnet

  service-storage:
    image: service-storage:fuego
    ports:
      - "8085:8085"
    links:
      - "db-storage"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-discovery-server:8761/eureka/
      # nota: non ha senso che sia 3306, ma non funziona con 3307
      - spring.datasource.url=jdbc:mysql://db-storage:3306/storage_db?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      - spring.datasource.username=root
      - spring.datasource.password=root
    depends_on:
      - db-storage
      - service-discovery-server
      - rabbitmq
    networks:
      - opnet

  # CLIENT
  service-client:
    image: service-client:fuego
    ports:
      - "5173:5173"
    networks:
      - opnet

networks:
  opnet:
    driver: bridge
