version: '3.8'
services:
  auth-service:
    image: auth-service:latest
    ports:
      - "8081:8081"
    links:
      - "userdb"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-discovery-server:8761/eureka/
      - spring.datasource.url=jdbc:mysql://userdb:3306/taas_db?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      - DB_HOST=userdb
      - DB_PORT=3306
      - DB_DATABASE=taas_db
    depends_on:
      - userdb
      - service-discovery-server
    networks:
      - opnet
    build:
      context: ./demo

    
  service-discovery-server:
    image: service_discovery_server
    ports:
      - "8761:8761"
    expose:
      - "8761"
    networks:
      - opnet

  api-gateway:
    image: api_gateway
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-discovery-server:8761/eureka/
    ports:
      - "8080:8080"
    depends_on:
      - service-discovery-server
    networks:
      - opnet
  
  userdb:
    image: mysql:8.1.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      DATABASE_HOST: userdb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taas_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      
    ports:
      - "3306:3306"
    networks:
      - opnet

  phpmyadmin:
     image: phpmyadmin/phpmyadmin
     container_name: taas_pma
     links:
       - userdb
     environment:
       PMA_HOST: userdb
       PMA_PORT: 3306
       PMA_ARBITRARY: 1
     restart: always
     ports:
       - 8067:80


networks:
  opnet:
    driver: bridge