version: "3.8"
services:
  # MANAGEMENT
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - opnet
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  service-discovery-server:
    image: service-discovery-server:latest
    ports:
      - "8761:8761"
    expose:
      - "8761"
    networks:
      - opnet

  service-gateway:
    image: service-gateway:latest
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-discovery-server:8761/eureka/
    ports:
      - "8080:8080"
    depends_on:
      - service-discovery-server
    networks:
      - opnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: taas_pma
    environment:
      PMA_HOST: userdb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8067:80
    networks:
      - opnet

  # AUTHENTICATION
  service-auth:
    image: service-auth:latest
    ports:
      - "8081:8081"
    links:
      - "userdb"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-discovery-server:8761/eureka/
      - spring.datasource.url=jdbc:mysql://userdb:3306/taas_db?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      - spring.datasource.username=root
      - spring.datasource.password=root
    depends_on:
      - userdb
      - service-discovery-server
    networks:
      - opnet

  userdb:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - opnet

  # REVIEWS
  service-reviews:
    image: service-reviews:latest
    ports:
      - "8083:8083"
    links:
      - "userdb"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-discovery-server:8761/eureka/
      - spring.datasource.url=jdbc:mysql://userdb:3306/taas_db?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      - spring.datasource.username=root
      - spring.datasource.password=root
    depends_on:
      - userdb
      - service-discovery-server
    networks:
      - opnet

networks:
  opnet:
    driver: bridge
