version: '3.7'
services:
 demo:
    image: filmserie:latest
    ports:
      - "8080:8080"
#    depends_on:
#      - db
 #     - phpmyadmin
 #   build:
 #     context: ./demo
 #     dockerfile: Dockerfile
 #   environment:
 #     SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/book_db?useSSL=false&allowPublicKeyRetrieval=true
#      SPRING_DATASOURCE_USERNAME: root
  #    SPRING_DATASOURCE_PASSWORD: root
 #   restart: always
