apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-gateway
  template:
    metadata:
      labels:
        app: service-gateway
    spec:
      containers:
        - name: service-gateway
          image: service-gateway:fuego
          ports:
            - containerPort: 8080
          env:
            - name: eureka.client.serviceUrl.defaultZone
              value: http://service-discovery-server:8761/eureka/
---
apiVersion: v1
kind: Service
metadata:
  name: service-gateway
spec:
  type: LoadBalancer 
  selector:
    app: service-gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
