apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-notifications
  template:
    metadata:
      labels:
        app: service-notifications
    spec:
      containers:
        - name: service-notifications
          image: service-notifications:fuego
          ports:
            - containerPort: 8081
          env:
            - name: eureka.client.serviceUrl.defaultZone
              value: http://service-discovery-server:8761/eureka/
---
apiVersion: v1
kind: Service
metadata:
  name: service-notifications
spec:
  selector:
    app: service-notifications
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
