apiVersion: apps/v1
kind: Deployment
metadata:
    name: service-users
spec:
    replicas: 1
    selector:
        matchLabels:
            app: service-users
    template:
        metadata:
            labels:
                app: service-users
        spec:
            containers:
            - 
                name: service-users
                image: service-users:latest
                ports:
                - containerPort: 8081
                env:
                - 
                    name: eureka.client.serviceUrl.defaultZone
                    value: http://service-discovery-server:8761/eureka/
                - 
                    name: spring.datasource.url
                    value: jdbc:mysql://db-user:3306/user_db?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
                - 
                    name: spring.datasource.username
                    value: root
                - 
                    name: spring.datasource.password
                    value: root
---
apiVersion: v1
kind: Service
metadata:
    name: service-users
spec:
    selector:
        app: service-users
    ports:
    - 
        protocol: TCP
        port: 8081
        targetPort: 8081