spring:
  application:
    name: reviewservice

eureka:
  instance:
    preferIpAddress: true
    appname: reviewservice
  client:
    serviceUrl:
      defaultZone: http://service-discovery-server:8761/eureka/
      #defaultZone: http://localhost:8761/eureka/


server:
  port: 8083