spring:
  application:
    name: service-auth

  # datasource:
  #   url: jdbc:mysql://localhost:3306/taas_db?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false&&createDatabaseIfNotExist=true
  #   username: root
  #   password: root
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    database-platform: org.hibernate.dialect.MySQL5Dialect

eureka:
  instance:
    preferIpAddress: true
    appname: service-auth
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://service-discovery-server:8761/eureka/


server:
  port: 8081