spring:
  application:
    name: demo
  main:
    allow-bean-definition-overriding: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 611783894582-gbcl6d7lidpkfpgjuk0qoihfe1tme2j9.apps.googleusercontent.com
            client-secret: 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

eureka:
  instance:
    preferIpAddress: true
    appname: demo
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://service-discovery-server:8761/eureka/

server:
  port: 8081
