spring:
  cloud:
    gateway:
      routes:
        - id: demo                 # id: You can give any id as of now.
          uri: lb://demo            # uri: Here you have to provide the port in which your microservice is running (demo)     
          predicates:              # predicates (- Path): Here we have provided the path “/demo/**”, which means any
            - Path=/demo/** # request starting with path “/demo/**” route it to DEMO-SERVICE.              
  application:
    name: api-gateway


eureka:
  instance:
    preferIpAddress: true
    appname: api-gateway
  client:
    serviceUrl:
      defaultZone: http://service-discovery-server:8761/eureka/


server:
  port: 8080