spring:
  cloud:
    gateway:
      routes:
        - id: demo
          uri: lb://demo
          predicates:
            - Path=/api/v1/user/**
  application:
    name: api-gateway


eureka:
  instance:
    preferIpAddress: true
    appname: api-gateway
  client:
    serviceUrl:
      defaultZone: http://service-discovery-server:8761/eureka/


server:
  port: 8080