spring:
  application:
    name: service-gateway
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin
  cloud:
    gateway:
      routes:
        - id: chat
          uri: lb://service-chat
          predicates:
            - Path=/chat/**
          filters:
            - AuthenticationFilter
        - id: review
          uri: lb://service-reviews
          predicates:
            - Path=/review/**
          filters:
            - AuthenticationFilter
        - id: notification
          uri: lb://service-notifications
          predicates:
            - Path=/notification/**
        - id: auth
          uri: lb://service-auth
          predicates:
            - Path=/friend/**
            - Path=/user/**
          filters:
            - AuthenticationFilter

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST

eureka:
  instance:
    #preferIpAddress: true
    appname: service-gateway
  client:
    serviceUrl:
      defaultZone: http://service-discovery-server:8761/eureka/
      #defaultZone: http://localhost:8761/eureka/


server:
  port: 8080