spring:
  application:
    name: service-reviews
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    database-platform: org.hibernate.dialect.MySQL5Dialect

eureka:
  instance:
    preferIpAddress: true
    appname: service-reviews
  client:
    serviceUrl:
      defaultZone: http://service-discovery-server:8761/eureka/
      #defaultZone: http://localhost:8761/eureka/